#!/usr/bin/bash

katexDir=$1
katexBase="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist"

function loadIfNotFound {
    if [ -f "$1" ]
    then
        echo "[+] found: $1"
        return
    fi
    echo "[+] loaded: $1"
    curl -Ls -o "$1" "$2"
}
function loadKatexFonts() {
    echo "[*] downloading katex into \"$katexDir\"..."
    mkdir -p "$katexDir"
    mkdir -p "$katexDir/fonts"
    loadIfNotFound "$katexDir/katex.min.js" "$katexBase/katex.min.js"
    loadIfNotFound "$katexDir/katex.min.css" "$katexBase/katex.min.css"

    grep -Eo 'fonts/[^)]+' "$katexDir/katex.min.css" |
        sed 's,^fonts/,,g' | while read url
    do
        loadIfNotFound "$katexDir/fonts/$url" "$katexBase/fonts/$url"
    done
}

[ -z "$katexDir" ] && echo usage: $0 '<output directory>' && exit

if [ -d "$katexDir" ] 
then
    echo "[+] found $katexDir"
else
    loadKatexFonts
fi
[ -d "$katexDir" ] || loadKatexFonts
