#!/usr/bin/bash

dir=$1
katexBase="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist"

function loadIfNotFound {
    if [ -f "$1" ]
    then
        echo "[+] found: $1"
        return
    fi
    echo "[+] loaded: $1"
    curl -Ls -o "$1" "$2"
}
function loadKatexFonts() {
    echo "[*] downloading katex into \"$dir\"..."
    mkdir -p "$dir"
    mkdir -p "$dir/fonts"
    loadIfNotFound "$dir/katex.min.js" "$katexBase/katex.min.js"
    loadIfNotFound "$dir/katex.min.css" "$katexBase/katex.min.css"

    grep -Eo 'fonts/[^)]+' "$dir/katex.min.css" |
        sed 's,^fonts/,,g' | while read url
    do
        loadIfNotFound "$dir/fonts/$url" "$katexBase/fonts/$url"
    done
}

function loadFiraCode() {
    echo "[***] downloading fira code into \"$dir\""
    loadIfNotFound "$dir/fira-code.css" "https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap"
}

[ -z "$dir" ] && echo usage: $0 '<output directory>' && exit

if [ -d "$dir" ]
then
    echo "[+] found $1"
else
fi
